#pragma once

#include <kaixa/foundation/diagnostic.hpp>
#include <kaixa/model/graph.hpp>

#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <vector>

namespace kaixa::plugin::cmake::detail {
    enum class DependencyMode {
        add_subdirectory,
        find_package
    };

    enum class TargetType {
        executable,
        static_library,
        shared_library,
        interface_library
    };

    struct DependencyOption {
        PackageId package;
        DependencyMode mode = DependencyMode::add_subdirectory;
    };

    struct TargetOptions {
        TargetType type = TargetType::executable;
        std::vector<std::string> sources;
        std::vector<std::string> include_directories;
        std::vector<std::string> public_include_directories;
        std::vector<std::string> link_libraries;
        std::vector<std::string> public_link_libraries;
        std::optional<std::int64_t> cxx_standard;
    };

    struct Options {
        std::filesystem::path source;
        std::vector<std::string> languages;
        std::optional<TargetOptions> target;
        std::vector<DependencyOption> dependencies;
    };

    inline constexpr std::string_view generated_marker =
        "# Generated by Kaixa from Kaixa.toml. Do not edit.";

    [[nodiscard]] Result<Options> read_options(const Graph& graph, const PackageNode& package);
    [[nodiscard]] DependencyMode dependency_mode(const Options& options, PackageId dependency);
    [[nodiscard]] std::string generate_project(const PackageNode& package, const Options& options);
}
