#pragma once

#include <kaixa/foundation/diagnostic.hpp>
#include <kaixa/model/effective_product.hpp>
#include <kaixa/model/graph.hpp>
#include <kaixa/test/adapter.hpp>

#include <cstdint>
#include <filesystem>
#include <map>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace kaixa::plugin::cmake::detail {
    inline constexpr std::string_view test_target_label_prefix = "kaixa.target:";

    enum class DependencyMode {
        add_subdirectory,
        find_package
    };

    enum class TargetType {
        executable,
        static_library,
        shared_library,
        interface_library
    };

    enum class GenerationMode {
        source,
        state
    };

    enum class MsvcRuntime {
        default_runtime,
        static_runtime,
        dynamic_runtime
    };

    struct DependencyOption {
        PackageId package;
        DependencyMode mode = DependencyMode::add_subdirectory;
    };

    struct TargetOptions {
        struct RuntimeFile {
            std::filesystem::path source;
            std::filesystem::path destination;
            bool directory = false;
        };

        struct InstallHeader {
            std::filesystem::path source;
            std::filesystem::path destination;
        };

        std::string name;
        TargetType type = TargetType::executable;
        std::vector<std::string> sources;
        std::vector<std::string> include_directories;
        std::vector<std::string> public_include_directories;
        std::vector<std::string> system_include_directories;
        std::vector<std::string> public_system_include_directories;
        std::vector<std::string> link_libraries;
        std::vector<std::string> public_link_libraries;
        std::vector<std::string> compile_definitions;
        std::vector<std::string> public_compile_definitions;
        std::vector<std::string> compile_options;
        std::vector<std::string> public_compile_options;
        std::vector<std::string> link_options;
        std::vector<std::string> precompiled_headers;
        std::vector<RuntimeFile> runtime_files;
        std::vector<InstallHeader> install_headers;
        std::optional<std::int64_t> cxx_standard;
        MsvcRuntime msvc_runtime = MsvcRuntime::default_runtime;
        bool default_build = true;
        bool install = false;
    };

    struct TestOptions {
        std::string name;
        std::string target;
        std::vector<std::string> arguments;
        TestAdapterInfo adapter;
    };

    struct Options {
        std::filesystem::path source;
        std::vector<std::string> languages;
        GenerationMode generation = GenerationMode::source;
        MsvcRuntime msvc_runtime = MsvcRuntime::default_runtime;
        std::optional<std::filesystem::path> runtime_output;
        std::optional<std::filesystem::path> library_output;
        std::optional<std::filesystem::path> archive_output;
        std::vector<TargetOptions> targets;
        std::vector<TestOptions> tests;
        std::vector<DependencyOption> dependencies;
        std::vector<std::string> find_packages;
        std::string policy_fingerprint;
    };

    struct BuildOptions {
        std::optional<std::string> generator;
        std::optional<std::string> c_compiler;
        std::optional<std::string> cxx_compiler;
        std::optional<std::filesystem::path> toolchain;
        std::vector<std::string> configure_arguments;
        std::vector<std::string> build_arguments;
        std::vector<std::string> install_arguments;
    };

    struct ConfigurationCacheKey {
        PackageId package;
        std::string configured_context;
        std::optional<std::string> policy;

        [[nodiscard]] bool operator==(const ConfigurationCacheKey&) const = default;
        [[nodiscard]] auto operator<=>(const ConfigurationCacheKey&) const = default;
    };

    struct ConfigurationCache {
        explicit ConfigurationCache(const std::size_t package_count = 0)
            : effective_packages(package_count) {}

        std::vector<std::optional<EffectivePackage>> effective_packages;
        std::map<ConfigurationCacheKey, Options> options;
        std::optional<std::vector<bool>> install_requirements;
        FileCatalog files;
    };

    inline constexpr std::string_view generated_marker = "# Generated by Kaixa from Kaixa.toml. Do not edit.";

    [[nodiscard]] Result<const Options*> read_cached_options(
        const Graph& graph,
        const ExtensionRegistry& registry,
        const PackageNode& package,
        const ProductRealizationContext& realization,
        const EffectivePolicy* policy_override,
        std::string_view configured_context,
        ConfigurationCache& cache
    );
    [[nodiscard]] Result<BuildOptions> read_build_options(const Value* settings);
    [[nodiscard]] DependencyMode dependency_mode(const Options& options, PackageId dependency);
    [[nodiscard]] std::string generate_project(const PackageNode& package, const Options& options);
}
