#pragma once

#include <kaixa/foundation/diagnostic.hpp>
#include <kaixa/model/graph.hpp>

#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <vector>

namespace kaixa::plugin::cmake::detail {
    enum class DependencyMode {
        add_subdirectory,
        find_package
    };

    enum class TargetType {
        executable,
        static_library,
        shared_library,
        interface_library
    };

    enum class GenerationMode {
        source,
        state
    };

    enum class MsvcRuntime {
        default_runtime,
        static_runtime,
        dynamic_runtime
    };

    struct DependencyOption {
        PackageId package;
        DependencyMode mode = DependencyMode::add_subdirectory;
    };

    struct TargetOptions {
        std::string name;
        TargetType type = TargetType::executable;
        std::vector<std::string> sources;
        std::vector<std::string> include_directories;
        std::vector<std::string> public_include_directories;
        std::vector<std::string> system_include_directories;
        std::vector<std::string> public_system_include_directories;
        std::vector<std::string> link_libraries;
        std::vector<std::string> public_link_libraries;
        std::vector<std::string> compile_definitions;
        std::vector<std::string> public_compile_definitions;
        std::vector<std::string> compile_options;
        std::vector<std::string> public_compile_options;
        std::optional<std::int64_t> cxx_standard;
    };

    struct TestOptions {
        std::string name;
        std::string target;
        std::vector<std::string> arguments;
    };

    struct Options {
        std::filesystem::path source;
        std::vector<std::string> languages;
        GenerationMode generation = GenerationMode::source;
        MsvcRuntime msvc_runtime = MsvcRuntime::default_runtime;
        std::optional<std::filesystem::path> runtime_output;
        std::optional<std::filesystem::path> library_output;
        std::optional<std::filesystem::path> archive_output;
        std::vector<TargetOptions> targets;
        std::vector<TestOptions> tests;
        std::vector<DependencyOption> dependencies;
    };

    struct BuildOptions {
        std::optional<std::string> generator;
        std::optional<std::string> c_compiler;
        std::optional<std::string> cxx_compiler;
        std::optional<std::filesystem::path> toolchain;
        std::vector<std::string> arguments;
    };

    inline constexpr std::string_view generated_marker =
        "# Generated by Kaixa from Kaixa.toml. Do not edit.";

    [[nodiscard]] Result<Options> read_options(const Graph& graph, const PackageNode& package);
    [[nodiscard]] Result<BuildOptions> read_build_options(const Value* settings);
    [[nodiscard]] DependencyMode dependency_mode(const Options& options, PackageId dependency);
    [[nodiscard]] std::string generate_project(const PackageNode& package, const Options& options);
}
