[package]
name = "kaixa"
version = "0.2.0-dev"
resolver = "cmake"
tests = ["tests"]

[cmake]
languages = ["CXX"]
generation = "source"
cxx-standard = 23
msvc-runtime = "static"
output = { runtime = "bin", library = "lib", archive = "lib" }

[[cmake.target]]
name = "kaixa_core"
type = "static-library"
sources = ["src/**/*.cpp"]
public-include-directories = ["include"]
system-include-directories = ["third_party"]
compile-definitions = ["TOML_EXCEPTIONS=0"]

[[cmake.target]]
name = "kaixa_plugins"
type = "static-library"
sources = ["plugins/**/*.cpp"]
public-include-directories = [
    "plugins/bundle/include",
    "plugins/cmake/include",
]
public-link-libraries = ["kaixa_core"]

[[cmake.target]]
name = "kaixa"
type = "executable"
sources = ["apps/kaixa/*.cpp"]
link-libraries = ["kaixa_core", "kaixa_plugins"]
