[package]
name = "kaixa"
version = "0.2.0-dev"
resolver = "cmake"
tests = ["tests"]
examples = ["examples"]
benchmarks = ["benchmarks"]

[package-set]
name = "kaixa"
default = ["kaixa"]

[package-set.policy]
cxx = 23
msvc-runtime = "static"

[dependencies]
kaixa_core = "0.2.0-dev"
kaixa_plugins = "0.2.0-dev"

[bin]
sources = ["apps/kaixa/*.cpp"]

[cmake]
languages = ["CXX"]
generation = "state"
msvc-runtime = "static"
output = { runtime = "bin", library = "lib", archive = "lib" }

[[config]]
name = "quality"

[config.cmake]
configure-arguments = ["-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"]

[members.kaixa_core]
version = "0.2.0-dev"
resolver = "cmake"

[members.kaixa_core.lib]
type = "static"
sources = ["src/**/*.cpp"]
public-include = ["include"]
system-include = ["third_party"]
defines = { TOML_EXCEPTIONS = 0 }

[members.kaixa_core.cmake]
generation = "state"

[members.kaixa_plugins]
version = "0.2.0-dev"
resolver = "cmake"

[members.kaixa_plugins.dependencies]
kaixa_core = "0.2.0-dev"

[members.kaixa_plugins.lib]
type = "static"
sources = ["plugins/**/*.cpp"]
public-include = [
    "plugins/bundle/include",
    "plugins/cmake/include",
    "plugins/path/include",
]

[members.kaixa_plugins.cmake]
generation = "state"
