# Generated by Kaixa from Kaixa.toml. Do not edit.
if(KAIXA_CMAKE_DEPENDENCIES_INCLUDED)
    return()
endif()
set(KAIXA_CMAKE_DEPENDENCIES_INCLUDED TRUE)
include(FetchContent)
if(POLICY CMP0169)
    cmake_policy(SET CMP0169 OLD)
endif()

