#pragma once

#include <model/project_model.hpp>

#include <kaixa/model/graph.hpp>

#include <span>
#include <string>
#include <string_view>

namespace kaixa::plugin::cmake::detail {
    // Generation turns the typed project model into CMake text. It resolves no dependency and
    // reads no manifest: everything it needs is already in `Options`.
    inline constexpr std::string_view generated_marker = "# Generated by Kaixa from Kaixa.toml. Do not edit.";

    struct ProjectPackage {
        const PackageNode* package = nullptr;
        const Options* options = nullptr;
    };

    [[nodiscard]] std::string source_variable(PackageId package);
    [[nodiscard]] std::string generate_project(std::span<const ProjectPackage> packages);
}
