[package]
name = "generated_hello"
version = "0.1.0"
resolver = "cmake"

[build]
default-configs = ["dev"]

[[config]]
name = "dev"
profile = "debug"

[cmake]
languages = ["CXX"]
type = "executable"
sources = ["src/main.cpp"]
cxx-standard = 23

[[cmake.test]]
name = "generated_hello"
target = "generated_hello"
